# This is an example configuration file for the N.I.N.A S3 Uploader
# Copy this file to config.yaml and modify it to suit your needs.

# Log configuration, one of debug, info, warn, error
log-level: info

s3:
  # The region to use
  region: us-east-1
  # The bucket to upload to
  bucket: YOUR_BUCKET_NAME
  # The prefix to use for the uploaded files
  prefix: /
  # The endpoint to use
  endpoint: https://s3.amazonaws.com

uploader:
  # The directory to watch for new files
  directory: R:\
  # The file extensions to watch for
  extensions:
    - .fits

  # Files are only stored locally if they fail to upload to S3
  # If the file is successfully uploaded at a later time, it is
  # deleted from the local directory
  local:
    directory: C:\Users\your\directory
