# Sample configuration
# Log level, one of debug, info, warn or error
log-level: "info"
s3:
  # The region to use
  region: "us-east-1"
  # The bucket to upload to
  # bucket: ""
  # The prefix to use for the uploaded files
  prefix: "/"
  # A custom S3-compatible endpoint URL, such as https://minio.example.com. Empty uses AWS
  # endpoint: ""
uploader:
  # The directory to watch for new files
  # directory: ""
  # The file extensions to watch for, such as .fits. Comma-separated in an environment variable
  # extensions: []
  local:
    # Files are only stored here if they fail to upload to S3. Once a file uploads at a later time, it is deleted from this directory
    # directory: ""
  # How long to wait after a file is uploaded or moved to the local directory before removing it from the watched directory, such as 30s
  # delay: "0s"
