// Code generated by configulator. DO NOT EDIT.
//
//go:build goexperiment.jsonv2

package config

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/USA-RedDragon/configulator/v2"
	cpflag "github.com/USA-RedDragon/configulator/v2/flags/pflag"
	"github.com/USA-RedDragon/configulator/v2/impl"
	"github.com/spf13/pflag"
)

type s3Shadow struct {
	Region   *string `json:"region"   toml:"region"   yaml:"region"`
	Bucket   *string `json:"bucket"   toml:"bucket"   yaml:"bucket"`
	Prefix   *string `json:"prefix"   toml:"prefix"   yaml:"prefix"`
	Endpoint *string `json:"endpoint" toml:"endpoint" yaml:"endpoint"`
}

type localShadow struct {
	Directory *string `json:"directory" toml:"directory" yaml:"directory"`
}

type uploaderShadow struct {
	Directory  *string        `json:"directory"  toml:"directory"  yaml:"directory"`
	Extensions *[]string      `json:"extensions" toml:"extensions" yaml:"extensions"`
	Local      *localShadow   `json:"local"      toml:"local"      yaml:"local"`
	Delay      *impl.Duration `json:"delay"      toml:"delay"      yaml:"delay"`
}

type configShadow struct {
	LogLevel *string         `json:"log-level" toml:"log-level" yaml:"log-level"`
	S3       *s3Shadow       `json:"s3"        toml:"s3"        yaml:"s3"`
	Uploader *uploaderShadow `json:"uploader"  toml:"uploader"  yaml:"uploader"`
}

// ConfigSchema returns the generated schema for Config.
func ConfigSchema() *configulator.Schema[Config] {
	return &configulator.Schema[Config]{
		ApplyDefaults: configApplyDefaults,
		ApplyEnv:      configApplyEnv,
		DecodeFile:    configDecodeFile,
		Required:      []string{"s3.bucket", "uploader.directory", "uploader.extensions", "uploader.local.directory"},
	}
}

func configApplyDefaults(cfg *Config, _ string, set configulator.SetOrigin) error {
	cfg.LogLevel = LogLevel("info")
	set("log-level", configulator.LayerDefault, "default tag")
	cfg.S3.Region = "us-east-1"
	set("s3.region", configulator.LayerDefault, "default tag")
	cfg.S3.Prefix = "/"
	set("s3.prefix", configulator.LayerDefault, "default tag")
	return nil
}

func configDecodeFile(data []byte, u configulator.Unmarshal, cfg *Config, sep string, set configulator.SetOrigin, file string) error {
	var sh configShadow
	if err := u(data, &sh); err != nil {
		return &configulator.DecodeError{
			Err:  err,
			Path: file,
		}
	}
	return sh.applyTo(cfg, sep, set, file)
}

func (s *configShadow) applyTo(cfg *Config, _ string, set configulator.SetOrigin, file string) error {
	if s.LogLevel != nil {
		cfg.LogLevel = LogLevel(*s.LogLevel)
		set("log-level", configulator.LayerFile, file)
	}
	if s.S3 != nil {
		if s.S3.Region != nil {
			cfg.S3.Region = *s.S3.Region
			set("s3.region", configulator.LayerFile, file)
		}
		if s.S3.Bucket != nil {
			cfg.S3.Bucket = *s.S3.Bucket
			set("s3.bucket", configulator.LayerFile, file)
		}
		if s.S3.Prefix != nil {
			cfg.S3.Prefix = *s.S3.Prefix
			set("s3.prefix", configulator.LayerFile, file)
		}
		if s.S3.Endpoint != nil {
			cfg.S3.Endpoint = *s.S3.Endpoint
			set("s3.endpoint", configulator.LayerFile, file)
		}
	}
	if s.Uploader != nil {
		if s.Uploader.Directory != nil {
			cfg.Uploader.Directory = *s.Uploader.Directory
			set("uploader.directory", configulator.LayerFile, file)
		}
		if s.Uploader.Extensions != nil {
			cfg.Uploader.Extensions = *s.Uploader.Extensions
			set("uploader.extensions", configulator.LayerFile, file)
		}
		if s.Uploader.Local != nil {
			if s.Uploader.Local.Directory != nil {
				cfg.Uploader.Local.Directory = *s.Uploader.Local.Directory
				set("uploader.local.directory", configulator.LayerFile, file)
			}
		}
		if s.Uploader.Delay != nil {
			v, ok := s.Uploader.Delay.Value()
			if !ok {
				return &configulator.OpaqueSpellingError{
					Hint: "\"30s\"",
					Path: "uploader.delay",
				}
			}
			cfg.Uploader.Delay = v
			set("uploader.delay", configulator.LayerFile, file)
		}
	}
	return nil
}

func configApplyEnv(cfg *Config, ec configulator.EnvContext, set configulator.SetOrigin) error {
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "log-level"); ok {
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "s3", "region"); ok {
		cfg.S3.Region = v
		set("s3.region", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "s3", "bucket"); ok {
		cfg.S3.Bucket = v
		set("s3.bucket", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "s3", "prefix"); ok {
		cfg.S3.Prefix = v
		set("s3.prefix", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "s3", "endpoint"); ok {
		cfg.S3.Endpoint = v
		set("s3.endpoint", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "uploader", "directory"); ok {
		cfg.Uploader.Directory = v
		set("uploader.directory", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "uploader", "extensions"); ok {
		lst := impl.SplitList(v, ec.ArraySeparator)
		cfg.Uploader.Extensions = lst
		set("uploader.extensions", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "uploader", "local", "directory"); ok {
		cfg.Uploader.Local.Directory = v
		set("uploader.local.directory", configulator.LayerEnv, n)
	}
	if n, v, ok := impl.LookupEnv(ec.Getenv, ec.Opts.Prefix, ec.Opts.Separator, "uploader", "delay"); ok {
		d, err := time.ParseDuration(v)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "uploader.delay",
				Source: n,
				Value:  v,
			}
		}
		cfg.Uploader.Delay = d
		set("uploader.delay", configulator.LayerEnv, n)
	}
	return nil
}

// ConfigPFlagHooks returns the pflag hooks for Config.
func ConfigPFlagHooks() cpflag.Hooks[Config] {
	return cpflag.Hooks[Config]{
		Apply:    configApplyPFlags,
		Register: configRegisterPFlags,
	}
}

func configRegisterPFlags(fs *pflag.FlagSet, o *cpflag.Options) error {
	names := []string{
		"log-level",
		"s3" + o.Separator + "region",
		"s3" + o.Separator + "bucket",
		"s3" + o.Separator + "prefix",
		"s3" + o.Separator + "endpoint",
		"uploader" + o.Separator + "directory",
		"uploader" + o.Separator + "extensions",
		"uploader" + o.Separator + "local" + o.Separator + "directory",
		"uploader" + o.Separator + "delay",
	}
	for i, name := range names {
		if f := fs.Lookup(name); f != nil {
			return &configulator.FlagConflictError{
				Existing: f.Name,
				Flag:     name,
			}
		}
		if slices.Contains(names[:i], name) {
			return &configulator.FlagConflictError{
				Existing: name,
				Flag:     name,
			}
		}
	}
	fs.String(names[0], "info", "Log level, one of debug, info, warn or error")
	fs.String(names[1], "us-east-1", "The region to use")
	fs.String(names[2], "", "The bucket to upload to")
	fs.String(names[3], "/", "The prefix to use for the uploaded files")
	fs.String(names[4], "", "A custom S3-compatible endpoint URL, such as https://minio.example.com. Empty uses AWS")
	fs.String(names[5], "", "The directory to watch for new files")
	fs.StringSlice(names[6], nil, "The file extensions to watch for, such as .fits. Comma-separated in an environment variable")
	fs.String(names[7], "", "Files are only stored here if they fail to upload to S3. Once a file uploads at a later time, it is deleted from this directory")
	fs.Duration(names[8], 0, "How long to wait after a file is uploaded or moved to the local directory before removing it from the watched directory")
	return nil
}

func configApplyPFlags(cfg *Config, fs *pflag.FlagSet, o *cpflag.Options, _ string, set configulator.SetOrigin) error {
	if n := "log-level"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "log-level",
				Source: "--" + n,
			}
		}
		cfg.LogLevel = LogLevel(v)
		set("log-level", configulator.LayerCLI, "--"+n)
	}
	if n := "s3" + o.Separator + "region"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "s3.region",
				Source: "--" + n,
			}
		}
		cfg.S3.Region = v
		set("s3.region", configulator.LayerCLI, "--"+n)
	}
	if n := "s3" + o.Separator + "bucket"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "s3.bucket",
				Source: "--" + n,
			}
		}
		cfg.S3.Bucket = v
		set("s3.bucket", configulator.LayerCLI, "--"+n)
	}
	if n := "s3" + o.Separator + "prefix"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "s3.prefix",
				Source: "--" + n,
			}
		}
		cfg.S3.Prefix = v
		set("s3.prefix", configulator.LayerCLI, "--"+n)
	}
	if n := "s3" + o.Separator + "endpoint"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "s3.endpoint",
				Source: "--" + n,
			}
		}
		cfg.S3.Endpoint = v
		set("s3.endpoint", configulator.LayerCLI, "--"+n)
	}
	if n := "uploader" + o.Separator + "directory"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "uploader.directory",
				Source: "--" + n,
			}
		}
		cfg.Uploader.Directory = v
		set("uploader.directory", configulator.LayerCLI, "--"+n)
	}
	if n := "uploader" + o.Separator + "extensions"; fs.Changed(n) {
		v, err := fs.GetStringSlice(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "uploader.extensions",
				Source: "--" + n,
			}
		}
		cfg.Uploader.Extensions = v
		set("uploader.extensions", configulator.LayerCLI, "--"+n)
	}
	if n := "uploader" + o.Separator + "local" + o.Separator + "directory"; fs.Changed(n) {
		v, err := fs.GetString(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "uploader.local.directory",
				Source: "--" + n,
			}
		}
		cfg.Uploader.Local.Directory = v
		set("uploader.local.directory", configulator.LayerCLI, "--"+n)
	}
	if n := "uploader" + o.Separator + "delay"; fs.Changed(n) {
		v, err := fs.GetDuration(n)
		if err != nil {
			return &configulator.ParseError{
				Err:    err,
				Path:   "uploader.delay",
				Source: "--" + n,
			}
		}
		cfg.Uploader.Delay = v
		set("uploader.delay", configulator.LayerCLI, "--"+n)
	}
	return nil
}

func (s *configShadow) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	tok, err := dec.ReadToken()
	if err != nil {
		return err
	}
	if tok.Kind() != jsontext.KindBeginObject {
		return fmt.Errorf("expected an object, got %v", tok.Kind())
	}
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "log-level":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.LogLevel = &str
			default:
				return configJSONError("log-level", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "s3":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("s3", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub s3Shadow
				if err := sub.decodeJSON(dec, "s3"); err != nil {
					return err
				}
				s.S3 = &sub
			}
		case "uploader":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError("uploader", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub uploaderShadow
				if err := sub.decodeJSON(dec, "uploader"); err != nil {
					return err
				}
				s.Uploader = &sub
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

var _ json.UnmarshalerFrom = (*configShadow)(nil)

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *s3Shadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "region":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Region = &str
			default:
				return configJSONError(path+".region", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "bucket":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Bucket = &str
			default:
				return configJSONError(path+".bucket", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "prefix":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Prefix = &str
			default:
				return configJSONError(path+".prefix", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "endpoint":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Endpoint = &str
			default:
				return configJSONError(path+".endpoint", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *uploaderShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "directory":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Directory = &str
			default:
				return configJSONError(path+".directory", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		case "extensions":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginArray {
					return configJSONError(path+".extensions", open, fmt.Errorf("expected an array, got %v", open.Kind()))
				}
				out := []string{}
				for dec.PeekKind() != jsontext.KindEndArray {
					v, err := dec.ReadToken()
					if err != nil {
						return err
					}
					if v.Kind() != jsontext.KindString {
						return configJSONError(path+".extensions"+"["+strconv.Itoa(len(out))+"]", v, fmt.Errorf("expected a string, got %v", v.Kind()))
					}
					el := v.String()
					out = append(out, el)
				}
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
				s.Extensions = &out
			}
		case "local":
			if dec.PeekKind() == jsontext.KindNull {
				if _, err := dec.ReadToken(); err != nil {
					return err
				}
			} else {
				open, err := dec.ReadToken()
				if err != nil {
					return err
				}
				if open.Kind() != jsontext.KindBeginObject {
					return configJSONError(path+".local", open, fmt.Errorf("expected an object, got %v", open.Kind()))
				}
				var sub localShadow
				if err := sub.decodeJSON(dec, path+".local"); err != nil {
					return err
				}
				s.Local = &sub
			}
		case "delay":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				var slot impl.Duration
				if err := slot.UnmarshalText([]byte(v.String())); err != nil {
					return configJSONError(path+".delay", v, err)
				}
				s.Delay = &slot
			default:
				return configJSONError(path+".delay", v, fmt.Errorf("expected a text scalar (e.g. \"30s\"), got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// decodeJSON decodes the members of an object whose opening brace has
// been read. path is the object's dotted path.
func (s *localShadow) decodeJSON(dec *jsontext.Decoder, path string) error {
	for {
		tok, err := dec.ReadToken()
		if err != nil {
			return err
		}
		if tok.Kind() == jsontext.KindEndObject {
			return nil
		}
		switch key := tok.String(); key {
		case "directory":
			v, err := dec.ReadToken()
			if err != nil {
				return err
			}
			switch v.Kind() {
			case jsontext.KindNull:
			case jsontext.KindString:
				str := v.String()
				s.Directory = &str
			default:
				return configJSONError(path+".directory", v, fmt.Errorf("expected a string, got %v", v.Kind()))
			}
		default:
			if reject, _ := json.GetOption(dec.Options(), json.RejectUnknownMembers); reject {
				return &configulator.UnknownKeyError{Path: path + "." + configQuoteKey(key)}
			}
			if err := dec.SkipValue(); err != nil {
				return err
			}
		}
	}
}

// configJSONError returns a ParseError for the JSON token v at path.
func configJSONError(path string, v jsontext.Token, err error) error {
	return &configulator.ParseError{
		Err:   err,
		Path:  path,
		Value: v.String(),
	}
}

// PrintConfig renders every field as "path = value" lines, redacting
// fields tagged secret:"true". The origin Report holds no values,
// so this is the only place redaction happens.
func (c Config) PrintConfig() string {
	var b strings.Builder
	fmt.Fprintf(&b, "log-level = %v\n", c.LogLevel)
	fmt.Fprintf(&b, "s3.region = %v\n", c.S3.Region)
	fmt.Fprintf(&b, "s3.bucket = %v\n", c.S3.Bucket)
	fmt.Fprintf(&b, "s3.prefix = %v\n", c.S3.Prefix)
	fmt.Fprintf(&b, "s3.endpoint = %v\n", c.S3.Endpoint)
	fmt.Fprintf(&b, "uploader.directory = %v\n", c.Uploader.Directory)
	fmt.Fprintf(&b, "uploader.extensions = %v\n", c.Uploader.Extensions)
	fmt.Fprintf(&b, "uploader.local.directory = %v\n", c.Uploader.Local.Directory)
	fmt.Fprintf(&b, "uploader.delay = %v\n", c.Uploader.Delay)
	return b.String()
}

func configQuoteKey(k string) string {
	if strings.ContainsAny(k, ".[") {
		return "\"" + strings.NewReplacer("\\", "\\\\", "\"", "\\\"").Replace(k) + "\""
	}
	return k
}
